export const ONBOARDING_CATEGORIES_OF_INTEREST = [{
    value: 1,
    viewValue: 'Arts',
    image: 'assets/banners/flippingfive.jpg'
}, {
    value: 2,
    viewValue: 'News',
    image: 'assets/banners/flippingfive.jpg'
}, {
    value: 3,
    viewValue: 'Society',
    image: 'assets/banners/flippingfive.jpg'
}, {
    value: 4,
    viewValue: 'Business',
    image: 'assets/banners/flippingfive.jpg'
}, {
    value: 5,
    viewValue: 'Health',
    image: 'assets/banners/flippingfive.jpg'
}, {
    value: 6,
    viewValue: 'Recreation',
    image: 'assets/banners/flippingfive.jpg'
}, {
    value: 7,
    viewValue: 'Science',
    image: 'assets/banners/flippingfive.jpg'
}, {
    value: 8,
    viewValue: 'Sports',
    image: 'assets/banners/flippingfive.jpg'
}, {
    value: 9,
    viewValue: 'Computers',
    image: 'assets/banners/flippingfive.jpg'
}, {
    value: 10,
    viewValue: 'Shopping',
    image: 'assets/banners/flippingfive.jpg'
}, {
    value: 11,
    viewValue: 'Family',
    image: 'assets/banners/flippingfive.jpg'
}, {
    value: 12,
    viewValue: 'Space',
    image: 'assets/banners/flippingfive.jpg'
}];
